name: Loon to Egern Converter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run conversion
      run: |
        mkdir -p outputs
        for file in examples/*.loon; do
          filename=$(basename "$file" .loon)
          python src/converter.py "$file" > "outputs/${filename}.yaml"
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: egern-configs
        path: outputs/
