name: Convert Loon Plugin to Egern Module

# 触发条件
on:
  push:
    paths:
      - 'Loon/Plugin/**'  # 仅当 Loon/Plugin 文件夹有变化时触发

# 任务
jobs:
  convert:
    runs-on: ubuntu-latest  # 使用 Ubuntu 虚拟机

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # 使用最新 Python 3.x 版本

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      # 4. 运行转换脚本
      - name: Run conversion script
        run: |
          python .github/scripts/convert.py

      # 5. 检查是否有文件变化并提交
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add Egern/Module/*
          git diff-index --quiet HEAD || git commit -m "Auto-convert Loon plugins to Egern modules"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}