name: Loon2Egern Converter
on:
  push:
    paths:
      - 'Loon/Plugin/*.plugin'  # 监控Loon插件目录
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pyyaml jinja2

    - name: Convert files
      run: |
        # 创建输出目录
        mkdir -p Egern/Module
        
        # 遍历所有Loon插件
        for input_file in Loon/Plugin/*.plugin; do
          # 生成输出路径（保留文件名，扩展名改为yaml）
          filename=$(basename "$input_file" .plugin)
          output_file="Egern/Module/${filename}.yaml"
          
          # 执行转换
          python src/converter.py "$input_file" "$output_file"
        done

    - name: Commit results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Egern/Module/
        git commit -m "Auto-generated Egern modules"
        git push
