name: Convert SOCKS5 Proxies

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  workflow_dispatch:  # 支持手动触发

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run conversion script
        run: python convert.py

      - name: Commit converted file
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add converted_proxies.txt
          git diff --quiet && git diff --staged --quiet || git commit -m 'Update converted_proxies.txt'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}