name: Convert Loon to Egern

on:
  push:
    paths:
      - 'Tool/Loon/Plugin/*.plugin'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Convert plugins
        shell: bash
        run: |
          set -euo pipefail
          LOON_DIR="Tool/Loon/Plugin"
          EGERN_DIR="Tool/Egern/Module"
          
          find "$LOON_DIR" -name '*.plugin' -print0 | while IFS= read -r -d $'\0' file; do
            base=$(basename "$file" .plugin)
            output="$EGERN_DIR/$base.yaml"
            
            awk '/^#!/{gsub(/^#!/,""); print}' "$file" | awk -F= '{
              if(/name/) print "name:", $2
              if(/desc/) print "description:", $2
              if(/author/) print "author:", $2
            }' > "$output"
            
            echo -e "\n# Converted at: $(date '+%Y-%m-%d %H:%M:%S')\n" >> "$output"

            process_rule() {
              sed -E "/^$1/!d; s/^$1\s*//; s/^/  - /"
            }
            
            echo "rules:" >> "$output"
            grep -E '^(http-response|RULE|MITM)' "$file" | process_rule ".*" >> "$output"
          done

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Auto Converter"
          git config --global user.email "converter@noreply.github.com"
          git add "Tool/Egern/Module"
          git diff --cached --quiet || git commit -m "Auto-converted Loon plugins"
          git push
