name: Convert Loon Plugin to Egern YAML

on:
  push:
    branches:
      - main
    paths:
      - 'Loon/Plugin/**/*.plugin'

jobs:
  convert-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: pip install pyyaml

      - name: 运行转换脚本
        run: python convert_plugin_to_yaml.py

      - name: 提交并推送到 Egern 仓库
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "GitHub Actions"
          git add Egern/Module/
          git commit -m "自动转换 Loon 插件到 Egern 模块"
          git push